name: Bump Version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Update package.json
        uses: jossef/action-set-json-field@890d7642122dbb2833dddd2003659bb71a2b21fe
        with:
          file: package.json
          field: version
          value: ${{ github.event.inputs.version }}
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Bump version to ${{ github.event.inputs.version }}"
          git tag -a ${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"

      - name: Push changes
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa
        with:
          github_token: ${{ secrets.TOKEN }}
          tags: true